import argparse
import struct
import subprocess
from pathlib import Path


TARGET_SAMPLE_RATE = 24000
TARGET_PEAK = 30000


def decode_pcm(ffmpeg_path: str, source: Path) -> list[int]:
    cmd = [
        ffmpeg_path,
        "-v",
        "error",
        "-i",
        str(source),
        "-ac",
        "1",
        "-ar",
        str(TARGET_SAMPLE_RATE),
        "-f",
        "s16le",
        "-",
    ]
    raw = subprocess.check_output(cmd)
    if len(raw) % 2 != 0:
        raise RuntimeError("decoded PCM byte count is not 16-bit aligned")
    return list(struct.unpack(f"<{len(raw) // 2}h", raw))


def trim_tail(samples: list[int], threshold: int = 256) -> list[int]:
    end = len(samples)
    while end > 0 and abs(samples[end - 1]) < threshold:
        end -= 1
    return samples[:end]


def normalize(samples: list[int], target_peak: int) -> list[int]:
    peak = max(abs(v) for v in samples) if samples else 0
    if peak == 0:
        return samples

    scale = min(1.0, target_peak / peak) if peak > target_peak else (target_peak / peak)
    scaled = []
    for value in samples:
        out = int(round(value * scale))
        if out > 32767:
            out = 32767
        if out < -32768:
            out = -32768
        scaled.append(out)
    return scaled


def quantize_to_s8(samples: list[int]) -> list[int]:
    out = []
    for value in samples:
        quantized = int(round(value / 256.0))
        if quantized > 127:
            quantized = 127
        if quantized < -128:
            quantized = -128
        out.append(quantized)
    return out


def write_mem(mem_path: Path, samples: list[int]) -> None:
    with mem_path.open("w", encoding="ascii", newline="\n") as handle:
        for sample in samples:
            handle.write(f"{sample & 0xFF:02X}\n")


def write_meta(meta_path: Path, sample_count: int) -> None:
    with meta_path.open("w", encoding="ascii", newline="\n") as handle:
        handle.write("// Auto-generated by scripts/audio/generate_validation_tone.py\n")
        handle.write(f"`define AUDIO_VALIDATION_SAMPLE_COUNT 16'd{sample_count}\n")
        handle.write(f"`define AUDIO_VALIDATION_SAMPLE_RATE 16'd{TARGET_SAMPLE_RATE}\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ffmpeg", required=True)
    parser.add_argument("--input", required=True)
    parser.add_argument("--mem", required=True)
    parser.add_argument("--meta", required=True)
    args = parser.parse_args()

    source = Path(args.input)
    mem_path = Path(args.mem)
    meta_path = Path(args.meta)

    samples = decode_pcm(args.ffmpeg, source)
    samples = trim_tail(samples)
    samples = normalize(samples, TARGET_PEAK)
    samples = quantize_to_s8(samples)

    mem_path.parent.mkdir(parents=True, exist_ok=True)
    write_mem(mem_path, samples)
    write_meta(meta_path, len(samples))

    peak = max(abs(v) for v in samples) if samples else 0
    print(f"wrote {len(samples)} samples to {mem_path}")
    print(f"peak={peak} sample_rate={TARGET_SAMPLE_RATE} format=s8")


if __name__ == "__main__":
    main()
