#!/usr/bin/env python3
"""Generate the LVGL C font for the PIXEL GBA UI.

The source font is TakWolf's Fusion Pixel Font zh_hans 12px monospaced TTF.
This script enumerates the font cmap and asks lv_font_conv to include every
Unicode codepoint the TTF actually provides. Nearby ranges are merged to keep
the Windows command line short while still producing a full Simplified Chinese
pixel font.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import shutil
import subprocess
import sys
from pathlib import Path

from fontTools.ttLib import TTFont


REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_FONT = REPO_ROOT / "src/ps/app/src/ThirdParty/fonts/fusion-pixel-font/fusion-pixel-12px-monospaced-zh_hans.ttf"
DEFAULT_OUTPUT = REPO_ROOT / "src/ps/app/src/Ui/Assets/Fonts/ps_ui_font_fusion_12.c"


def _collect_codepoints(font_path: Path) -> list[int]:
    font = TTFont(font_path)
    codepoints: set[int] = set()
    for table in font["cmap"].tables:
        if table.isUnicode():
            codepoints.update(table.cmap.keys())
    return sorted(cp for cp in codepoints if cp >= 0x20 and cp != 0x7F)


def _merge_ranges(codepoints: list[int], max_gap: int) -> list[tuple[int, int]]:
    ranges: list[tuple[int, int]] = []
    start: int | None = None
    prev: int | None = None

    for cp in codepoints:
        if start is None or prev is None:
            start = cp
            prev = cp
            continue
        if cp <= prev + max_gap + 1:
            prev = cp
            continue
        ranges.append((start, prev))
        start = cp
        prev = cp

    if start is not None and prev is not None:
        ranges.append((start, prev))
    return ranges


def _format_range(range_pair: tuple[int, int]) -> str:
    start, end = range_pair
    if start == end:
        return f"0x{start:X}"
    return f"0x{start:X}-0x{end:X}"


def _write_header(output: Path, args: argparse.Namespace, glyph_count: int, range_count: int) -> None:
    text = output.read_text(encoding="utf-8")
    generated_at = _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    try:
        font_label = args.font.relative_to(REPO_ROOT).as_posix()
    except ValueError:
        font_label = args.font.as_posix()
    header = (
        "/*******************************************************************************\n"
        " * Generated by scripts/fonts/gen_lvgl_fusion_font.py\n"
        f" * Source font: {font_label}\n"
        " * Source project: TakWolf/fusion-pixel-font\n"
        " * Font license: SIL Open Font License 1.1\n"
        f" * Glyph codepoints: {glyph_count}\n"
        f" * Merged lv_font_conv ranges: {range_count}\n"
        f" * Generated: {generated_at}\n"
        " * Options: --size 12 --bpp 1 --format lvgl --no-kerning --no-compress --lv-include lvgl.h\n"
        " ******************************************************************************/\n"
    )
    if text.startswith("/*******************************************************************************"):
        end = text.find(" ******************************************************************************/")
        if end >= 0:
            end = text.find("\n", end)
            text = text[end + 1 :]
    output.write_text(header + text, encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--font", type=Path, default=DEFAULT_FONT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--lv-font-name", default="ps_ui_font_fusion_12")
    parser.add_argument("--merge-gap", type=int, default=256)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    args.font = args.font.resolve()
    args.output = args.output.resolve()

    codepoints = _collect_codepoints(args.font)
    ranges = _merge_ranges(codepoints, args.merge_gap)
    range_arg = ",".join(_format_range(item) for item in ranges)

    print(f"[font] source={args.font}")
    print(f"[font] codepoints={len(codepoints)} merged_ranges={len(ranges)} range_arg_bytes={len(range_arg)}")
    if args.dry_run:
        print(range_arg)
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    npx = shutil.which("npx") or shutil.which("npx.cmd")
    if npx is None:
        print("[font] npx was not found in PATH", file=sys.stderr)
        return 1

    cmd = [
        npx,
        "lv_font_conv",
        "--size",
        "12",
        "--bpp",
        "1",
        "--format",
        "lvgl",
        "--font",
        str(args.font),
        "--range",
        range_arg,
        "--no-kerning",
        "--no-compress",
        "--lv-include",
        "lvgl.h",
        "--lv-font-name",
        args.lv_font_name,
        "-o",
        str(args.output),
    ]
    subprocess.run(cmd, cwd=REPO_ROOT, check=True)
    _write_header(args.output, args, len(codepoints), len(ranges))
    return 0


if __name__ == "__main__":
    sys.exit(main())
